include: [".well-known"]

url: "https://gerardgascon.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Gerard Gascón" # the name of your site, e.g. ACME Corp.

collections:
  - projects
  - projectsall