services:
  web:
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
      - "35729:35729"
    command:
      - sh
      - -c
      - |
        bundle install
        jekyll serve --host 0.0.0.0 --force_polling --livereload --drafts --incremental
    restart: unless-stopped
